package MainJFrame;

import java.util.*;
import holdem.*;

public class MainJFrame extends javax.swing.JFrame {

    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlayer1 = new javax.swing.JButton();
        btnDealRiver = new javax.swing.JButton();
        btnPlayer2 = new javax.swing.JButton();
        btnDealFlop = new javax.swing.JButton();
        btnDealTurn = new javax.swing.JButton();
        lblPlayer1Card = new javax.swing.JLabel();
        lblPlayer2Card = new javax.swing.JLabel();
        lblBoard = new javax.swing.JLabel();
        btnShuffle = new javax.swing.JButton();
        btnPlayer1Bet = new javax.swing.JButton();
        btnPlayer2Bet = new javax.swing.JButton();
        btnPlayer1Win = new javax.swing.JButton();
        btnPlayer2Win = new javax.swing.JButton();
        txtPlayer1Bet = new javax.swing.JTextField();
        txtPlayer2Bet = new javax.swing.JTextField();
        lblPlayer1Stack = new javax.swing.JLabel();
        lblPlayer2Stack = new javax.swing.JLabel();
        lblPot = new javax.swing.JLabel();
        lblPotValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlayer1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer1.setText("Player 1");
        btnPlayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer1MouseClicked(evt);
            }
        });
        btnPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1ActionPerformed(evt);
            }
        });

        btnDealRiver.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealRiver.setText("Deal River");
        btnDealRiver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealRiverMouseClicked(evt);
            }
        });
        btnDealRiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealRiverActionPerformed(evt);
            }
        });

        btnPlayer2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer2.setText("Player 2");
        btnPlayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer2MouseClicked(evt);
            }
        });
        btnPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2ActionPerformed(evt);
            }
        });

        btnDealFlop.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealFlop.setText("Deal Flop");
        btnDealFlop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealFlopMouseClicked(evt);
            }
        });
        btnDealFlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealFlopActionPerformed(evt);
            }
        });

        btnDealTurn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealTurn.setText("Deal Turn");
        btnDealTurn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealTurnMouseClicked(evt);
            }
        });
        btnDealTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealTurnActionPerformed(evt);
            }
        });

        lblPlayer1Card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblPlayer2Card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblBoard.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        btnShuffle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnShuffle.setText("Shuffle");
        btnShuffle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShuffleMouseClicked(evt);
            }
        });
        btnShuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShuffleActionPerformed(evt);
            }
        });

        btnPlayer1Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer1Bet.setText("Bet");
        btnPlayer1Bet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer1BetMouseClicked(evt);
            }
        });

        btnPlayer2Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer2Bet.setText("Bet");
        btnPlayer2Bet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer2BetMouseClicked(evt);
            }
        });

        btnPlayer1Win.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer1Win.setText("Player 1 Win");
        btnPlayer1Win.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer1WinMouseClicked(evt);
            }
        });

        btnPlayer2Win.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer2Win.setText("Player 2 Win");
        btnPlayer2Win.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer2WinMouseClicked(evt);
            }
        });

        txtPlayer1Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtPlayer2Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblPlayer1Stack.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPlayer1Stack.setText("jLabel1");

        lblPlayer2Stack.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPlayer2Stack.setText("jLabel1");

        lblPot.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPot.setText("Pot");

        lblPotValue.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPotValue.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPlayer1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlayer1Card, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDealTurn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPlayer2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlayer2Card, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlayer1Bet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlayer2Bet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlayer1Bet, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtPlayer2Bet)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDealFlop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDealRiver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShuffle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblPot))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayer2Stack, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPlayer1Stack))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer1Win)
                    .addComponent(btnPlayer2Win)
                    .addComponent(lblPotValue))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPot)
                    .addComponent(lblPotValue)
                    .addComponent(btnShuffle))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPlayer1Card, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer1)
                    .addComponent(btnPlayer1Bet)
                    .addComponent(txtPlayer1Bet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayer1Stack)
                    .addComponent(btnPlayer1Win))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPlayer2Win)
                    .addComponent(lblPlayer2Stack)
                    .addComponent(txtPlayer2Bet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer2Bet)
                    .addComponent(btnPlayer2)
                    .addComponent(lblPlayer2Card, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDealFlop)
                    .addComponent(lblBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDealTurn)
                .addGap(18, 18, 18)
                .addComponent(btnDealRiver)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer1ActionPerformed

    private void btnDealRiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealRiverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealRiverActionPerformed

    private void btnPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer2ActionPerformed

    private void btnDealFlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealFlopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealFlopActionPerformed

    private void btnDealTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealTurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealTurnActionPerformed

    private void btnShuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShuffleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShuffleActionPerformed

    private void btnShuffleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShuffleMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < 52; i++) {
            holdem.cards[i] = i + 1;
        }
        holdem.shuffle();
        lblBoard.setText("");
    }//GEN-LAST:event_btnShuffleMouseClicked

    private void btnPlayer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer1MouseClicked
        // TODO add your handling code here:
        if (holdem.player1Show == false) {
            lblPlayer1Card.setText(holdem.toString(holdem.cards[1]) + ' ' + holdem.toString(holdem.cards[2]));
            holdem.player1Show = true;
        } else {
            lblPlayer1Card.setText("");
            holdem.player1Show = false;
        }
    }//GEN-LAST:event_btnPlayer1MouseClicked

    private void btnPlayer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer2MouseClicked
        // TODO add your handling code here:
        if (holdem.player2Show == false) {
            lblPlayer2Card.setText(holdem.toString(holdem.cards[3]) + ' ' + holdem.toString(holdem.cards[4]));
            holdem.player2Show = true;
        } else {
            lblPlayer2Card.setText("");
            holdem.player2Show = false;
        }
    }//GEN-LAST:event_btnPlayer2MouseClicked

    private void btnDealFlopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealFlopMouseClicked
        // TODO add your handling code here:
        lblBoard.setText(holdem.toString(holdem.cards[5]) + ' ' + holdem.toString(holdem.cards[6]) + ' ' + holdem.toString(holdem.cards[7]));
    }//GEN-LAST:event_btnDealFlopMouseClicked

    private void btnDealTurnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealTurnMouseClicked
        // TODO add your handling code here:
        lblBoard.setText(holdem.toString(holdem.cards[5]) + ' ' + holdem.toString(holdem.cards[6]) + ' ' + holdem.toString(holdem.cards[7]) + ' ' + holdem.toString(holdem.cards[8]));
    }//GEN-LAST:event_btnDealTurnMouseClicked

    private void btnDealRiverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealRiverMouseClicked
        // TODO add your handling code here:
        lblBoard.setText(holdem.toString(holdem.cards[5]) + ' ' + holdem.toString(holdem.cards[6]) + ' ' + holdem.toString(holdem.cards[7]) + ' ' + holdem.toString(holdem.cards[8]) + ' ' + holdem.toString(holdem.cards[9]));
    }//GEN-LAST:event_btnDealRiverMouseClicked

    private void btnPlayer1BetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer1BetMouseClicked
        // TODO add your handling code here:
        holdem.player1Stack -= Integer.parseInt(txtPlayer1Bet.getText());
        lblPlayer1Stack.setText(Integer.toString(holdem.player1Stack));
        holdem.pot += Integer.parseInt(txtPlayer1Bet.getText());
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer1BetMouseClicked

    private void btnPlayer2BetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer2BetMouseClicked
        // TODO add your handling code here:
        holdem.player2Stack -= Integer.parseInt(txtPlayer2Bet.getText());
        lblPlayer2Stack.setText(Integer.toString(holdem.player2Stack));
        holdem.pot += Integer.parseInt(txtPlayer2Bet.getText());
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer2BetMouseClicked

    private void btnPlayer1WinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer1WinMouseClicked
        // TODO add your handling code here:
        holdem.player1Stack += holdem.pot;
        lblPlayer1Stack.setText(Integer.toString(holdem.player1Stack));
        holdem.pot = 0;
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer1WinMouseClicked

    private void btnPlayer2WinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer2WinMouseClicked
        // TODO add your handling code here:
        holdem.player2Stack += holdem.pot;
        lblPlayer2Stack.setText(Integer.toString(holdem.player2Stack));
        holdem.pot = 0;
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer2WinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    private Holdem holdem = new Holdem();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDealFlop;
    private javax.swing.JButton btnDealRiver;
    private javax.swing.JButton btnDealTurn;
    private javax.swing.JButton btnPlayer1;
    private javax.swing.JButton btnPlayer1Bet;
    private javax.swing.JButton btnPlayer1Win;
    private javax.swing.JButton btnPlayer2;
    private javax.swing.JButton btnPlayer2Bet;
    private javax.swing.JButton btnPlayer2Win;
    private javax.swing.JButton btnShuffle;
    private javax.swing.JLabel lblBoard;
    private javax.swing.JLabel lblPlayer1Card;
    private javax.swing.JLabel lblPlayer1Stack;
    private javax.swing.JLabel lblPlayer2Card;
    private javax.swing.JLabel lblPlayer2Stack;
    private javax.swing.JLabel lblPot;
    private javax.swing.JLabel lblPotValue;
    private javax.swing.JTextField txtPlayer1Bet;
    private javax.swing.JTextField txtPlayer2Bet;
    // End of variables declaration//GEN-END:variables
}
