package HoldemMainJFrame;

import java.util.*;
import holdem.*;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.awt.Component;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;

public class HoldemMainJFrame extends javax.swing.JFrame {

    public HoldemMainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlayer1 = new javax.swing.JButton();
        btnDealRiver = new javax.swing.JButton();
        btnPlayer2 = new javax.swing.JButton();
        btnDealFlop = new javax.swing.JButton();
        btnDealTurn = new javax.swing.JButton();
        lblPlayer1Card = new javax.swing.JLabel();
        lblPlayer2Card = new javax.swing.JLabel();
        lblBoard = new javax.swing.JLabel();
        btnShuffle = new javax.swing.JButton();
        btnPlayer1Bet = new javax.swing.JButton();
        btnPlayer2Bet = new javax.swing.JButton();
        btnPlayer1Win = new javax.swing.JButton();
        btnPlayer2Win = new javax.swing.JButton();
        txtPlayer1Bet = new javax.swing.JTextField();
        txtPlayer2Bet = new javax.swing.JTextField();
        lblPlayer1Stack = new javax.swing.JLabel();
        lblPlayer2Stack = new javax.swing.JLabel();
        lblPot = new javax.swing.JLabel();
        lblPotValue = new javax.swing.JLabel();
        btnShowBoardImage = new javax.swing.JToggleButton();
        pnlBoardImage = new javax.swing.JPanel();
        lblBoardImg2 = new javax.swing.JLabel();
        lblBoardImg4 = new javax.swing.JLabel();
        lblBoardImg1 = new javax.swing.JLabel();
        lblBoardImg3 = new javax.swing.JLabel();
        lblBoardImg0 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlayer1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer1.setText("Player 1");
        btnPlayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer1MouseClicked(evt);
            }
        });
        btnPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1ActionPerformed(evt);
            }
        });

        btnDealRiver.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealRiver.setText("Deal River");
        btnDealRiver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealRiverMouseClicked(evt);
            }
        });
        btnDealRiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealRiverActionPerformed(evt);
            }
        });

        btnPlayer2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer2.setText("Player 2");
        btnPlayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer2MouseClicked(evt);
            }
        });
        btnPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2ActionPerformed(evt);
            }
        });

        btnDealFlop.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealFlop.setText("Deal Flop");
        btnDealFlop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealFlopMouseClicked(evt);
            }
        });
        btnDealFlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealFlopActionPerformed(evt);
            }
        });

        btnDealTurn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealTurn.setText("Deal Turn");
        btnDealTurn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealTurnMouseClicked(evt);
            }
        });
        btnDealTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealTurnActionPerformed(evt);
            }
        });

        lblPlayer1Card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblPlayer2Card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblBoard.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        btnShuffle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnShuffle.setText("Shuffle");
        btnShuffle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShuffleMouseClicked(evt);
            }
        });
        btnShuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShuffleActionPerformed(evt);
            }
        });

        btnPlayer1Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer1Bet.setText("Bet");
        btnPlayer1Bet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer1BetMouseClicked(evt);
            }
        });

        btnPlayer2Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer2Bet.setText("Bet");
        btnPlayer2Bet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer2BetMouseClicked(evt);
            }
        });

        btnPlayer1Win.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer1Win.setText("Player 1 Win");
        btnPlayer1Win.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer1WinMouseClicked(evt);
            }
        });

        btnPlayer2Win.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer2Win.setText("Player 2 Win");
        btnPlayer2Win.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer2WinMouseClicked(evt);
            }
        });

        txtPlayer1Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtPlayer2Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblPlayer1Stack.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPlayer1Stack.setText("jLabel1");

        lblPlayer2Stack.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPlayer2Stack.setText("jLabel1");

        lblPot.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPot.setText("Pot");

        lblPotValue.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPotValue.setText("jLabel3");

        btnShowBoardImage.setText("Show Image");
        btnShowBoardImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowBoardImageMouseClicked(evt);
            }
        });
        btnShowBoardImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBoardImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBoardImageLayout = new javax.swing.GroupLayout(pnlBoardImage);
        pnlBoardImage.setLayout(pnlBoardImageLayout);
        pnlBoardImageLayout.setHorizontalGroup(
            pnlBoardImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoardImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBoardImg0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblBoardImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblBoardImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblBoardImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblBoardImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBoardImageLayout.setVerticalGroup(
            pnlBoardImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoardImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBoardImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBoardImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardImg0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPlayer1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlayer1Card, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPlayer2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlayer2Card, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlayer1Bet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlayer2Bet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlayer1Bet, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtPlayer2Bet)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDealFlop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addComponent(btnShuffle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDealTurn)
                            .addComponent(btnDealRiver))
                        .addGap(65, 65, 65)
                        .addComponent(pnlBoardImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowBoardImage)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblPot))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayer2Stack, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPlayer1Stack))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer1Win)
                    .addComponent(btnPlayer2Win)
                    .addComponent(lblPotValue))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBoardImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPot)
                            .addComponent(lblPotValue)
                            .addComponent(btnShuffle))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPlayer1Card, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlayer1)
                            .addComponent(btnPlayer1Bet)
                            .addComponent(txtPlayer1Bet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlayer1Stack)
                            .addComponent(btnPlayer1Win))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnPlayer2Win)
                            .addComponent(lblPlayer2Stack)
                            .addComponent(txtPlayer2Bet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlayer2Bet)
                            .addComponent(btnPlayer2)
                            .addComponent(lblPlayer2Card, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnDealFlop)
                            .addComponent(lblBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnDealTurn)
                                .addGap(18, 18, 18)
                                .addComponent(btnDealRiver))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnShowBoardImage)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer1ActionPerformed

    private void btnDealRiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealRiverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealRiverActionPerformed

    private void btnPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer2ActionPerformed

    private void btnDealFlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealFlopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealFlopActionPerformed

    private void btnDealTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealTurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealTurnActionPerformed

    private void btnShuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShuffleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShuffleActionPerformed

    private void btnShuffleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShuffleMouseClicked
        // TODO add your handling code here:
        holdem.shuffle();
        lblBoard.setText("");
        for (String s : board) {
            s = null;
        }
        hideBoardImage();
    }//GEN-LAST:event_btnShuffleMouseClicked

    private void btnPlayer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer1MouseClicked
        // TODO add your handling code here:
        if (player1Show == false) {
            lblPlayer1Card.setText(toString(holdem.getPlayerCard1(), " "));
            player1Show = true;
        } else {
            lblPlayer1Card.setText("");
            player1Show = false;
        }
    }//GEN-LAST:event_btnPlayer1MouseClicked

    private void btnPlayer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer2MouseClicked
        // TODO add your handling code here:
        if (player2Show == false) {
            lblPlayer2Card.setText(toString(holdem.getPlayerCard2(), " "));
            player2Show = true;
        } else {
            lblPlayer2Card.setText("");
            player2Show = false;
        }
    }//GEN-LAST:event_btnPlayer2MouseClicked

    private void btnDealFlopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealFlopMouseClicked
        // TODO add your handling code here:
        String[] flopArray = holdem.getFlop();
        flop = toString(flopArray, " ");
        System.arraycopy(flopArray, 0, board, 0, flopArray.length);
        lblBoard.setText(flop);
        if (boardImageShow) {
            showBoardImage();
        }
    }//GEN-LAST:event_btnDealFlopMouseClicked

    private void btnDealTurnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealTurnMouseClicked
        // TODO add your handling code here:
        turn = holdem.getTurn();
        board[3] = turn;
        lblBoard.setText(flop + " " + turn);
        if (boardImageShow) {
            showBoardImage();
        }
    }//GEN-LAST:event_btnDealTurnMouseClicked

    private void btnDealRiverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealRiverMouseClicked
        // TODO add your handling code here:
        river = holdem.getRiver();
        board[4] = river;
        lblBoard.setText(flop + " " + turn + " " + river);
        if (boardImageShow) {
            showBoardImage();
        }
    }//GEN-LAST:event_btnDealRiverMouseClicked

    private void btnPlayer1BetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer1BetMouseClicked
        // TODO add your handling code here:
        holdem.player1Stack -= Integer.parseInt(txtPlayer1Bet.getText());
        lblPlayer1Stack.setText(Integer.toString(holdem.player1Stack));
        holdem.pot += Integer.parseInt(txtPlayer1Bet.getText());
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer1BetMouseClicked

    private void btnPlayer2BetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer2BetMouseClicked
        // TODO add your handling code here:
        holdem.player2Stack -= Integer.parseInt(txtPlayer2Bet.getText());
        lblPlayer2Stack.setText(Integer.toString(holdem.player2Stack));
        holdem.pot += Integer.parseInt(txtPlayer2Bet.getText());
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer2BetMouseClicked

    private void btnPlayer1WinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer1WinMouseClicked
        // TODO add your handling code here:
        holdem.player1Stack += holdem.pot;
        lblPlayer1Stack.setText(Integer.toString(holdem.player1Stack));
        holdem.pot = 0;
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer1WinMouseClicked

    private void btnPlayer2WinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer2WinMouseClicked
        // TODO add your handling code here:
        holdem.player2Stack += holdem.pot;
        lblPlayer2Stack.setText(Integer.toString(holdem.player2Stack));
        holdem.pot = 0;
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer2WinMouseClicked

    private void btnShowBoardImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBoardImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowBoardImageActionPerformed

    private void btnShowBoardImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowBoardImageMouseClicked
        // TODO add your handling code here:
        if (!boardImageShow) {
            showBoardImage();
        } else {
            hideBoardImage();
        }
        boardImageShow = !boardImageShow;
    }//GEN-LAST:event_btnShowBoardImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoldemMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoldemMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoldemMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoldemMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoldemMainJFrame().setVisible(true);
            }
        });
    }
    private Holdem holdem = new Holdem();
    String[] board = new String[5];
    String flop;
    String turn;
    String river;
    public boolean player1Show = false;
    public boolean player2Show = false;
    public boolean boardImageShow = false;

    private String toString(String[] stringArray, String delimiter) {
        String s = "";
        for (String sa : stringArray) {
            s += sa + delimiter;
        }
        return s;
    }
    
    
    private void hideBoardImage() {
        for (int i = 0; i < board.length; i++) {
            hideBoardImageAt(i);
        }
    }
    
    private void hideBoardImageAt(int i) {
        JLabel lblBoardImg = (JLabel) pnlBoardImage.getComponent(i);
        lblBoardImg.setIcon(null);
    }
    
    private void showBoardImage() {
        for (int i = 0; i < board.length; i++) {
            if (board[i] == null) break;
            showBoardImageAt(i);
        }
    }
    
    private int showBoardImageAt(int i) {
        BufferedImage image = null;
        if (i >= board.length) {
            return 1;
        }
        try {
            System.out.println(board[i]);
            File imageFile = new File("resources/deck/" + board[i] + ".png");
            if (!imageFile.exists()) {
                String cardName = "";
                if (board[i].charAt(0) == 'T') {
                    cardName = "10" + board[i].charAt(1);
                }
                imageFile = new File("resources/deck/" + cardName + ".png");
            }
            image = ImageIO.read(imageFile);
        } catch (IOException ex) {
            System.out.println(ex);
        }
        int imageWidth = lblBoardImg0.getWidth();
        int imageHeight = lblBoardImg0.getHeight();
        Image cardImage = image.getScaledInstance(imageWidth, imageHeight, Image.SCALE_SMOOTH);
        ImageIcon cardImageIcon = new ImageIcon(cardImage);
        JLabel lblBoardImg = (JLabel) pnlBoardImage.getComponent(i);
        lblBoardImg.setIcon(cardImageIcon);
        return 0;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDealFlop;
    private javax.swing.JButton btnDealRiver;
    private javax.swing.JButton btnDealTurn;
    private javax.swing.JButton btnPlayer1;
    private javax.swing.JButton btnPlayer1Bet;
    private javax.swing.JButton btnPlayer1Win;
    private javax.swing.JButton btnPlayer2;
    private javax.swing.JButton btnPlayer2Bet;
    private javax.swing.JButton btnPlayer2Win;
    private javax.swing.JToggleButton btnShowBoardImage;
    private javax.swing.JButton btnShuffle;
    private javax.swing.JLabel lblBoard;
    private javax.swing.JLabel lblBoardImg0;
    private javax.swing.JLabel lblBoardImg1;
    private javax.swing.JLabel lblBoardImg2;
    private javax.swing.JLabel lblBoardImg3;
    private javax.swing.JLabel lblBoardImg4;
    private javax.swing.JLabel lblPlayer1Card;
    private javax.swing.JLabel lblPlayer1Stack;
    private javax.swing.JLabel lblPlayer2Card;
    private javax.swing.JLabel lblPlayer2Stack;
    private javax.swing.JLabel lblPot;
    private javax.swing.JLabel lblPotValue;
    private javax.swing.JPanel pnlBoardImage;
    private javax.swing.JTextField txtPlayer1Bet;
    private javax.swing.JTextField txtPlayer2Bet;
    // End of variables declaration//GEN-END:variables
}
