package HoldemMainJFrame;

import java.util.*;
import holdem.*;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.awt.Component;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;

public class HoldemMainJFrame extends javax.swing.JFrame {

    public HoldemMainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlayer1 = new javax.swing.JButton();
        btnDealRiver = new javax.swing.JButton();
        btnPlayer2 = new javax.swing.JButton();
        btnDealFlop = new javax.swing.JButton();
        btnDealTurn = new javax.swing.JButton();
        lblPlayer1Card = new javax.swing.JLabel();
        lblPlayer2Card = new javax.swing.JLabel();
        lblBoard = new javax.swing.JLabel();
        btnShuffle = new javax.swing.JButton();
        btnPlayer1Bet = new javax.swing.JButton();
        btnPlayer2Bet = new javax.swing.JButton();
        lblPlayer1Stack = new javax.swing.JLabel();
        lblPlayer2Stack = new javax.swing.JLabel();
        lblPot = new javax.swing.JLabel();
        lblPotValue = new javax.swing.JLabel();
        pnlBoardImg = new javax.swing.JPanel();
        lblBoardImg0 = new javax.swing.JLabel();
        lblBoardImg1 = new javax.swing.JLabel();
        lblBoardImg2 = new javax.swing.JLabel();
        lblBoardImg3 = new javax.swing.JLabel();
        lblBoardImg4 = new javax.swing.JLabel();
        btnShowBoardImage = new javax.swing.JToggleButton();
        pnlPlayer2Img = new javax.swing.JPanel();
        lblPlayer2Img0 = new javax.swing.JLabel();
        lblPlayer2Img1 = new javax.swing.JLabel();
        pnlPlayer1Img = new javax.swing.JPanel();
        lblPlayer1Img0 = new javax.swing.JLabel();
        lblPlayer1Img1 = new javax.swing.JLabel();
        jSliderPlayer1 = new javax.swing.JSlider();
        jSliderPlayer2 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlayer1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer1.setText("Player 1");
        btnPlayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer1MouseClicked(evt);
            }
        });
        btnPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1ActionPerformed(evt);
            }
        });

        btnDealRiver.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealRiver.setText("Deal River");
        btnDealRiver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealRiverMouseClicked(evt);
            }
        });
        btnDealRiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealRiverActionPerformed(evt);
            }
        });

        btnPlayer2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer2.setText("Player 2");
        btnPlayer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer2MouseClicked(evt);
            }
        });
        btnPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2ActionPerformed(evt);
            }
        });

        btnDealFlop.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealFlop.setText("Deal Flop");
        btnDealFlop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealFlopMouseClicked(evt);
            }
        });
        btnDealFlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealFlopActionPerformed(evt);
            }
        });

        btnDealTurn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDealTurn.setText("Deal Turn");
        btnDealTurn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDealTurnMouseClicked(evt);
            }
        });
        btnDealTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealTurnActionPerformed(evt);
            }
        });

        lblPlayer1Card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblPlayer2Card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblBoard.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnShuffle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnShuffle.setText("Shuffle");
        btnShuffle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShuffleMouseClicked(evt);
            }
        });
        btnShuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShuffleActionPerformed(evt);
            }
        });

        btnPlayer1Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer1Bet.setText("Bet");
        btnPlayer1Bet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer1BetMouseClicked(evt);
            }
        });

        btnPlayer2Bet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlayer2Bet.setText("Bet");
        btnPlayer2Bet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayer2BetMouseClicked(evt);
            }
        });

        lblPlayer1Stack.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPlayer1Stack.setText("jLabel1");

        lblPlayer2Stack.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPlayer2Stack.setText("jLabel2");

        lblPot.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPot.setText("Pot");

        lblPotValue.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPotValue.setText("jLabel3");

        javax.swing.GroupLayout pnlBoardImgLayout = new javax.swing.GroupLayout(pnlBoardImg);
        pnlBoardImg.setLayout(pnlBoardImgLayout);
        pnlBoardImgLayout.setHorizontalGroup(
            pnlBoardImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoardImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBoardImg0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBoardImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblBoardImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBoardImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBoardImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlBoardImgLayout.setVerticalGroup(
            pnlBoardImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoardImgLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(pnlBoardImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoardImg0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardImg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardImg2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardImg3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoardImg4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnShowBoardImage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnShowBoardImage.setText("Show Image");
        btnShowBoardImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowBoardImageMouseClicked(evt);
            }
        });
        btnShowBoardImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBoardImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPlayer2ImgLayout = new javax.swing.GroupLayout(pnlPlayer2Img);
        pnlPlayer2Img.setLayout(pnlPlayer2ImgLayout);
        pnlPlayer2ImgLayout.setHorizontalGroup(
            pnlPlayer2ImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayer2ImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayer2Img0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPlayer2Img1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlPlayer2ImgLayout.setVerticalGroup(
            pnlPlayer2ImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayer2ImgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlPlayer2ImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayer2Img0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayer2Img1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnlPlayer1ImgLayout = new javax.swing.GroupLayout(pnlPlayer1Img);
        pnlPlayer1Img.setLayout(pnlPlayer1ImgLayout);
        pnlPlayer1ImgLayout.setHorizontalGroup(
            pnlPlayer1ImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayer1ImgLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblPlayer1Img0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPlayer1Img1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPlayer1ImgLayout.setVerticalGroup(
            pnlPlayer1ImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayer1ImgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlPlayer1ImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayer1Img0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayer1Img1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDealTurn)
                                    .addComponent(btnDealRiver))
                                .addGap(18, 18, 18)
                                .addComponent(pnlBoardImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDealFlop)
                                .addGap(26, 26, 26)
                                .addComponent(lblBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayer1Card, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlayer1Stack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlPlayer2Img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblPlayer2Stack))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnPlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlPlayer1Img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(355, 355, 355)
                        .addComponent(lblPlayer2Card, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlayer1Bet)
                        .addGap(28, 28, 28)
                        .addComponent(jSliderPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSliderPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPlayer2Bet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer2))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnShuffle)
                .addGap(43, 43, 43)
                .addComponent(lblPot)
                .addGap(31, 31, 31)
                .addComponent(lblPotValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowBoardImage))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlayer1Bet)
                            .addComponent(btnPlayer1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPlayer2)
                                .addComponent(btnPlayer2Bet))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSliderPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSliderPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlPlayer1Img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblPlayer1Stack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlayer1Card, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlayer2Stack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlayer2Card, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlPlayer2Img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDealFlop)
                    .addComponent(lblBoard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBoardImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDealTurn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDealRiver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowBoardImage)
                    .addComponent(btnShuffle)
                    .addComponent(lblPot)
                    .addComponent(lblPotValue)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer1ActionPerformed

    private void btnDealRiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealRiverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealRiverActionPerformed

    private void btnPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer2ActionPerformed

    private void btnDealFlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealFlopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealFlopActionPerformed

    private void btnDealTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealTurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDealTurnActionPerformed

    private void btnShuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShuffleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShuffleActionPerformed

    private void btnShuffleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShuffleMouseClicked
        // TODO add your handling code here:
        holdem.shuffle();
        lblBoard.setText("");
        for (int i = 0; i < board.length; i++) {
            board[i] = null;
        }
        hideBoardImage();
    }//GEN-LAST:event_btnShuffleMouseClicked

    private void btnPlayer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer1MouseClicked
        // TODO add your handling code here:
        if (player1Show == false) {
            lblPlayer1Card.setText(toString(holdem.getPlayerCard1(), " "));
            showPlayerImage(1);
            player1Show = true;
        } else {
            lblPlayer1Card.setText("");
            player1Show = false;
        }
    }//GEN-LAST:event_btnPlayer1MouseClicked

    private void btnPlayer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer2MouseClicked
        // TODO add your handling code here:
        if (player2Show == false) {
            lblPlayer2Card.setText(toString(holdem.getPlayerCard2(), " "));
            showPlayerImage(2);
            player2Show = true;
        } else {
            lblPlayer2Card.setText("");
            player2Show = false;
        }
    }//GEN-LAST:event_btnPlayer2MouseClicked

    private void btnDealFlopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealFlopMouseClicked
        // TODO add your handling code here:
        String[] flopArray = holdem.getFlop();
        flop = toString(flopArray, " ");
        System.arraycopy(flopArray, 0, board, 0, flopArray.length);
        lblBoard.setText(flop);
        if (boardImageShow) {
            showBoardImage();
        }
    }//GEN-LAST:event_btnDealFlopMouseClicked

    private void btnDealTurnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealTurnMouseClicked
        // TODO add your handling code here:
        turn = holdem.getTurn();
        board[3] = turn;
        lblBoard.setText(flop + " " + turn);
        if (boardImageShow) {
            showBoardImage();
        }
    }//GEN-LAST:event_btnDealTurnMouseClicked

    private void btnDealRiverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDealRiverMouseClicked
        // TODO add your handling code here:
        river = holdem.getRiver();
        board[4] = river;
        lblBoard.setText(flop + " " + turn + " " + river);
        if (boardImageShow) {
            showBoardImage();
        }
    }//GEN-LAST:event_btnDealRiverMouseClicked

    private void btnPlayer1BetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer1BetMouseClicked
        // TODO add your handling code here:
        int player1BetValue = jSliderPlayer1.getValue();
        holdem.player1Stack -= player1BetValue;
        lblPlayer1Stack.setText(Integer.toString(holdem.player1Stack));
        holdem.pot += jSliderPlayer1.getValue();
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer1BetMouseClicked

    private void btnPlayer2BetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayer2BetMouseClicked
        // TODO add your handling code here:
        int player2BetValue = jSliderPlayer2.getValue();
        holdem.player2Stack -= player2BetValue;
        lblPlayer2Stack.setText(Integer.toString(holdem.player2Stack));
        holdem.pot += player2BetValue;
        lblPotValue.setText(Integer.toString(holdem.pot));
    }//GEN-LAST:event_btnPlayer2BetMouseClicked

    private void btnShowBoardImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBoardImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowBoardImageActionPerformed

    private void btnShowBoardImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowBoardImageMouseClicked
        // TODO add your handling code here:
        if (!boardImageShow) {
            showBoardImage();
        } else {
            hideBoardImage();
        }
        boardImageShow = !boardImageShow;
    }//GEN-LAST:event_btnShowBoardImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoldemMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoldemMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoldemMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoldemMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoldemMainJFrame().setVisible(true);
            }
        });
    }
    private Holdem holdem = new Holdem();
    String[] board = new String[5];
    String flop;
    String turn;
    String river;
    public boolean player1Show = false;
    public boolean player2Show = false;
    public boolean boardImageShow = false;

    private String toString(String[] stringArray, String delimiter) {
        String s = "";
        for (String sa : stringArray) {
            s += sa + delimiter;
        }
        return s;
    }

    private void hideBoardImage() {
        for (int i = 0; i < board.length; i++) {
            hideBoardImageAt(i);
        }
    }

    private void hideBoardImageAt(int i) {
        JLabel lblBoardImg = (JLabel) pnlBoardImg.getComponent(i);
        lblBoardImg.setIcon(null);
    }

    private void showBoardImage() {
        for (int i = 0; i < board.length; i++) {
            if (board[i] == null) {
                break;
            }
            showBoardImageAt(i);
        }
    }

    private void showPlayerImage(int playerNum) {
        String[] playerCardString1 = holdem.getPlayerCard1();
        String[] playerCardString2 = holdem.getPlayerCard2();
        String[] playerCardString = playerCardString1;
        JLabel[] cardLabel = new JLabel[2];
        JLabel lblPlayerCardImg0 = new JLabel();
        JLabel lblPlayerCardImg1 = new JLabel();
        if (playerNum == 1) {
            playerCardString = playerCardString1;
            lblPlayerCardImg0 = (JLabel) pnlPlayer1Img.getComponent(0);
            lblPlayerCardImg1 = (JLabel) pnlPlayer1Img.getComponent(1);
        } else {
            playerCardString = playerCardString2;
            lblPlayerCardImg0 = (JLabel) pnlPlayer2Img.getComponent(0);
            lblPlayerCardImg1 = (JLabel) pnlPlayer2Img.getComponent(1);
        }
        cardLabel[0] = lblPlayerCardImg0;
        cardLabel[1] = lblPlayerCardImg1;
        for (int i = 0; i < playerCardString.length; i++) {
            showCardImage(playerCardString[i], cardLabel[i]);

        }
    }

    private int showBoardImageAt(int i) {
        if (i >= board.length) {
            return 1;
        }
        JLabel lblBoardImg = (JLabel) pnlBoardImg.getComponent(i);
        showCardImage(board[i], lblBoardImg);
        return 0;
    }

    int showCardImage(String cardString, JLabel cardLabel) {
        BufferedImage image = null;
        try {
            System.out.println(cardString);
            File imageFile = new File("resources/deck/" + cardString + ".png");
            if (!imageFile.exists()) {
                String cardName = "";
                if (cardString.charAt(0) == 'T') {
                    cardName = "10" + cardString.charAt(1);
                }
                imageFile = new File("resources/deck/" + cardName + ".png");
            }
            image = ImageIO.read(imageFile);
        } catch (IOException ex) {
            System.out.println(ex);
        }
        int imageWidth = cardLabel.getWidth();
        int imageHeight = cardLabel.getHeight();
        Image cardImage = image.getScaledInstance(imageWidth, imageHeight, Image.SCALE_SMOOTH);
        ImageIcon cardImageIcon = new ImageIcon(cardImage);
        cardLabel.setIcon(cardImageIcon);
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDealFlop;
    private javax.swing.JButton btnDealRiver;
    private javax.swing.JButton btnDealTurn;
    private javax.swing.JButton btnPlayer1;
    private javax.swing.JButton btnPlayer1Bet;
    private javax.swing.JButton btnPlayer2;
    private javax.swing.JButton btnPlayer2Bet;
    private javax.swing.JToggleButton btnShowBoardImage;
    private javax.swing.JButton btnShuffle;
    private javax.swing.JSlider jSliderPlayer1;
    private javax.swing.JSlider jSliderPlayer2;
    private javax.swing.JLabel lblBoard;
    private javax.swing.JLabel lblBoardImg0;
    private javax.swing.JLabel lblBoardImg1;
    private javax.swing.JLabel lblBoardImg2;
    private javax.swing.JLabel lblBoardImg3;
    private javax.swing.JLabel lblBoardImg4;
    private javax.swing.JLabel lblPlayer1Card;
    private javax.swing.JLabel lblPlayer1Img0;
    private javax.swing.JLabel lblPlayer1Img1;
    private javax.swing.JLabel lblPlayer1Stack;
    private javax.swing.JLabel lblPlayer2Card;
    private javax.swing.JLabel lblPlayer2Img0;
    private javax.swing.JLabel lblPlayer2Img1;
    private javax.swing.JLabel lblPlayer2Stack;
    private javax.swing.JLabel lblPot;
    private javax.swing.JLabel lblPotValue;
    private javax.swing.JPanel pnlBoardImg;
    private javax.swing.JPanel pnlPlayer1Img;
    private javax.swing.JPanel pnlPlayer2Img;
    // End of variables declaration//GEN-END:variables
}
