name: Build Docker

on:
  pull_request:
    branches: [master]
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build java
        working-directory: ./server
        run: ./gradlew build
      - name: Build Docker image
        working-directory: ./server/
        run: docker build -t fanzengau/holdem-app:latest .
      - name: Push Docker image
        working-directory: ./server
        run: docker push fanzengau/holdem-app:latest
