name: Build Test Lib

on: [push]

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'
          architecture: x64
          cache: gradle
      - name: Run build with Gradle Wrapper
        run: |
          cd holdem  
          ./gradlew build
      - name: Run test with Gradle Wrapper
        run: |
          cd holdem
          ./gradlew test